[package]
name = "hiragana"
version = "0.1.0"
authors = ["Torkel <torkel@voysys.se>"]
edition = "2018"

[dependencies]
rand = "0.5"
google-translate2 = "1"
hyper = "^0.10"
hyper-rustls = "^0.6"
serde = "^1.0"
serde_json = "^1.0"
yup-oauth2 = "^1.0"
